server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo?useUnicode=true?charachterEncodeing=utf-8&useSSL=false
    password: 12121
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      connection-test-query: select 1
mybatis:
  mapper-locations: classpath:com/study/dubbo/provider/dao/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: user_provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881